import StyleDictionary from 'style-dictionary'
import { fileURLToPath } from 'url'
import path from 'path'
import fs from 'fs'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const tokensDir = __dirname
const outputDir = path.join(__dirname, 'themes')

// ---------------------------------------------------------------------------
// Custom format: renders CSS custom properties under configurable selectors.
// Light tokens go under the base selector, dark tokens under the dark selector.
// ---------------------------------------------------------------------------

StyleDictionary.registerFormat({
  name: 'css/ds-brand',
  format({ dictionary, options }) {
    const selector = options.selector || ':root'
    const darkSelector = options.darkSelector || null

    // Separate light vs dark tokens by path
    const lightTokens = dictionary.allTokens.filter(
      (t) => !t.path.includes('dark')
    )
    const darkTokens = dictionary.allTokens.filter(
      (t) => t.path.includes('dark')
    )

    const renderTokens = (tokens) =>
      tokens
        .map((t) => `  --ds-${t.name}: ${t.$value ?? t.value};`)
        .join('\n')

    let out = `/* Auto-generated by Style Dictionary — do not edit manually */\n\n`
    out += `${selector} {\n${renderTokens(lightTokens)}\n}\n`

    if (darkSelector && darkTokens.length > 0) {
      out += `\n${darkSelector} {\n${renderTokens(darkTokens)}\n}\n`
    }

    return out
  },
})

// ---------------------------------------------------------------------------
// Custom name transform: strip namespace/brand/mode prefixes, keep semantic path.
//
// Input path examples (after split-by-brand mode files):
//   ['brand','farco','font-size','sm']          → 'font-size-sm'
//   ['mode','light','color','action','background','primary'] → 'color-action-background-primary'
//   ['mode','dark','color','text','primary']     → 'color-text-primary'
// ---------------------------------------------------------------------------

StyleDictionary.registerTransform({
  name: 'name/ds/semantic',
  type: 'name',
  transform(token) {
    const p = [...token.path]

    // Drop 'brand' or 'mode' at index 0
    if (p[0] === 'brand' || p[0] === 'mode') p.shift()
    // Drop 'light' or 'dark' at index 0
    if (p[0] === 'light' || p[0] === 'dark') p.shift()
    // Drop brand name (farco / white-label) at index 0 — present in brand/ files
    if (p[0] === 'farco' || p[0] === 'white-label') p.shift()

    return p.join('-')
  },
})

// ---------------------------------------------------------------------------
// Build helper
// ---------------------------------------------------------------------------

function makeBuildConfig(brand) {
  // Farco is the default brand — apply its tokens to :root as fallback
  // so the app works before data-brand is set by JS.
  const selector = brand === 'farco'
    ? `:root, [data-brand="${brand}"]`
    : `[data-brand="${brand}"]`
  const darkSelector = `[data-brand="${brand}"][data-mode="dark"]`

  return {
    // Suppress collision warnings — light and dark tokens intentionally share
    // the same output name because our custom format separates them into
    // distinct CSS selectors ([data-brand] vs [data-brand][data-mode="dark"]).
    log: { verbosity: 'silent' },
    // 'include' files are available for reference resolution but NOT emitted
    include: [
      path.join(tokensDir, 'primitives/base.json'),
      path.join(tokensDir, 'primitives/farco.json'),
      path.join(tokensDir, 'primitives/white-label.json'),
    ],
    // 'source' files are the ones that get processed and emitted
    source: [
      path.join(tokensDir, `brand/${brand}.json`),
      path.join(tokensDir, `mode/light.${brand}.json`),
      path.join(tokensDir, `mode/dark.${brand}.json`),
    ],
    platforms: {
      css: {
        transformGroup: 'css',
        transforms: ['name/ds/semantic'],
        buildPath: `${outputDir}/`,
        files: [
          {
            destination: `${brand}.css`,
            format: 'css/ds-brand',
            // Emit only:
            //   1. brand tokens for THIS brand
            //   2. semantic mode tokens (light + dark) — already brand-specific by file
            // Exclude all primitives (they are in 'include', not 'source').
            filter(token) {
              const p = token.path
              if (p[0] === 'brand') return p[1] === brand
              if (p[0] === 'mode') return true
              return false
            },
            options: { selector, darkSelector },
          },
        ],
      },
    },
  }
}

// ---------------------------------------------------------------------------
// Run
// ---------------------------------------------------------------------------

async function run() {
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true })
  }

  for (const brand of ['farco', 'white-label']) {
    console.log(`\nBuilding tokens for brand: ${brand}`)
    const sd = new StyleDictionary(makeBuildConfig(brand))
    await sd.buildAllPlatforms()
    console.log(`  ✓ src/tokens/themes/${brand}.css`)
  }

  console.log('\nToken build complete.')
}

run().catch((err) => {
  console.error(err)
  process.exit(1)
})
