import StyleDictionary from 'style-dictionary';
import { promises as fs } from 'fs';
import path from 'path';

const TOKENS_DIR = 'src/tokens';
const BASE_DIR = `${TOKENS_DIR}/base`;
const THEMES_DIR = `${TOKENS_DIR}/themes`;
const TEMP_DIR = `${TOKENS_DIR}/temp`;

// ---------------------------------------------------------------------------
// Step 1 — Generate size / dimension / spacing JSON files programmatically.
// size.0 = 0px, size.N = N * 4px for N = 1…30
// ---------------------------------------------------------------------------
async function generateScaleFiles() {
  const STEPS = 30;
  const BASE = 4;

  const sizeTokens = { size: { $type: 'dimension' } };
  const dimTokens  = { dim:  { $type: 'dimension' } };
  const spacingTokens = { spacing: { $type: 'dimension' } };

  // Spacing only covers the semantic subset of the scale.
  // All 31 steps (0–30) are exposed via size and dim.
  // Spacing mirrors the full dim scale so consumers can use whichever layer suits.
  for (let n = 0; n <= STEPS; n++) {
    const px = n === 0 ? '0px' : `${n * BASE}px`;
    sizeTokens.size[n]    = { $value: px };
    dimTokens.dim[n]      = { $value: `{size.${n}}` };
    spacingTokens.spacing[n] = { $value: `{dim.${n}}` };
  }

  await Promise.all([
    fs.writeFile(`${BASE_DIR}/size.tokens.json`,    JSON.stringify(sizeTokens, null, 2)),
    fs.writeFile(`${BASE_DIR}/dimension.tokens.json`, JSON.stringify(dimTokens, null, 2)),
    fs.writeFile(`${BASE_DIR}/spacing.tokens.json`, JSON.stringify(spacingTokens, null, 2)),
  ]);

  console.log('✔ Generated size / dimension / spacing token files (0–120)');
}

// ---------------------------------------------------------------------------
// Step 2 — Register shared Style Dictionary transforms
// ---------------------------------------------------------------------------
function registerTransforms() {
  // Name transform: join path, strip 'default', prepend 'farco'
  StyleDictionary.registerTransform({
    name: 'name/farco',
    type: 'name',
    transform: (token) => {
      const segments = token.path.filter((s) => s !== 'default');
      return ['farco', ...segments].join('-');
    },
  });

  // Shadow composite → CSS box-shadow string
  StyleDictionary.registerTransform({
    name: 'value/shadow-to-css',
    type: 'value',
    filter: (token) => token.$type === 'shadow' || token.type === 'shadow',
    transform: (token) => {
      const v = token.$value ?? token.value;
      const { offsetX, offsetY, blur, spread, color } = v;
      return `${offsetX} ${offsetY} ${blur} ${spread} ${color}`;
    },
  });

  // fontFamily array → CSS comma-separated string
  StyleDictionary.registerTransform({
    name: 'value/font-family-to-css',
    type: 'value',
    filter: (token) => token.$type === 'fontFamily' || token.type === 'fontFamily',
    transform: (token) => {
      const v = token.$value ?? token.value;
      if (Array.isArray(v)) {
        return v.map((f) => (f.includes(' ') ? `'${f}'` : f)).join(', ');
      }
      return v;
    },
  });

  StyleDictionary.registerTransformGroup({
    name: 'farco/css',
    transforms: ['name/farco', 'value/shadow-to-css', 'value/font-family-to-css'],
  });
}

// ---------------------------------------------------------------------------
// Step 3 — Build helper
// ---------------------------------------------------------------------------
async function buildToTemp({ label, sources, outputFile, selector, filterFn }) {
  const sd = new StyleDictionary({
    usesDtcg: true,
    log: { verbosity: 'default', warnings: 'disabled' },
    source: sources,
    platforms: {
      css: {
        transformGroup: 'farco/css',
        files: [
          {
            destination: outputFile,
            format: 'css/variables',
            filter: filterFn,
            options: {
              selector,
              outputReferences: true,
              fileHeader: false,
            },
          },
        ],
      },
    },
  });

  await sd.buildAllPlatforms();
  console.log(`  ✔ ${label} → ${outputFile}`);
}

// ---------------------------------------------------------------------------
// Step 4 — Concat light + dark temp files into a single branded theme file
// ---------------------------------------------------------------------------
async function concatTheme({ brand, lightTemp, darkTemp, outFile }) {
  const [light, dark] = await Promise.all([
    fs.readFile(lightTemp, 'utf8'),
    fs.readFile(darkTemp, 'utf8'),
  ]);

  const header = [
    '/**',
    ` * Auto-generated by Style Dictionary — do not edit manually.`,
    ` * Brand: ${brand}`,
    ` * Source: src/tokens/primitives/${brand}  +  src/tokens/semantic/${brand}`,
    ' */',
    '',
  ].join('\n');

  // Strip the per-file headers SD writes to the temp files
  const stripHeader = (css) => css.replace(/\/\*[\s\S]*?\*\/\s*\n/, '');

  await fs.writeFile(outFile, header + stripHeader(light) + '\n' + stripHeader(dark));
  console.log(`  ✔ Merged → ${outFile}`);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------
async function main() {
  await generateScaleFiles();

  registerTransforms();

  // Tokens from semantic files have paths starting with 'color'
  const isSemanticToken = (token) => token.path[0] === 'color';

  const BASE_SOURCES = [
    `${BASE_DIR}/size.tokens.json`,
    `${BASE_DIR}/dimension.tokens.json`,
    `${BASE_DIR}/spacing.tokens.json`,
    `${BASE_DIR}/typography.tokens.json`,
    `${BASE_DIR}/border-radius.tokens.json`,
    `${BASE_DIR}/shadow.tokens.json`,
    `${BASE_DIR}/misc.tokens.json`,
  ];

  console.log('\nBuilding farco…');
  await buildToTemp({
    label: 'farco light',
    sources: [...BASE_SOURCES,
      `${TOKENS_DIR}/primitives/farco/*.tokens.json`,
      `${TOKENS_DIR}/semantic/farco/light.tokens.json`,
    ],
    outputFile: `${TEMP_DIR}/farco-light.css`,
    selector: ':root, .theme-farco',
  });

  await buildToTemp({
    label: 'farco dark',
    sources: [
      `${TOKENS_DIR}/primitives/farco/*.tokens.json`,
      `${TOKENS_DIR}/semantic/farco/dark.tokens.json`,
    ],
    outputFile: `${TEMP_DIR}/farco-dark.css`,
    selector: '.theme-farco-dark',
    filterFn: isSemanticToken,
  });

  await concatTheme({
    brand: 'farco',
    lightTemp: `${TEMP_DIR}/farco-light.css`,
    darkTemp:  `${TEMP_DIR}/farco-dark.css`,
    outFile:   `${THEMES_DIR}/farco.css`,
  });

  console.log('\nBuilding white-label…');
  await buildToTemp({
    label: 'white-label light',
    sources: [...BASE_SOURCES,
      `${TOKENS_DIR}/primitives/white-label/*.tokens.json`,
      `${TOKENS_DIR}/semantic/white-label/light.tokens.json`,
    ],
    outputFile: `${TEMP_DIR}/white-label-light.css`,
    selector: '.theme-white-label',
  });

  await buildToTemp({
    label: 'white-label dark',
    sources: [
      `${TOKENS_DIR}/primitives/white-label/*.tokens.json`,
      `${TOKENS_DIR}/semantic/white-label/dark.tokens.json`,
    ],
    outputFile: `${TEMP_DIR}/white-label-dark.css`,
    selector: '.theme-white-label-dark',
    filterFn: isSemanticToken,
  });

  await concatTheme({
    brand: 'white-label',
    lightTemp: `${TEMP_DIR}/white-label-light.css`,
    darkTemp:  `${TEMP_DIR}/white-label-dark.css`,
    outFile:   `${THEMES_DIR}/white-label.css`,
  });

  console.log('\nDone.\n');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
